/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class _ObjectMemoryStorage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _ObjectMemoryStorage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_ObjectMemoryStorage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected _ObjectMemoryStorage() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete__ObjectMemoryStorage(swigCPtr);
    }
    swigCPtr = 0;
  }

  public _ObjectMemoryStorage(int initial_size) {
    this(tstJNI.new__ObjectMemoryStorage(initial_size), true);
  }

  public SWIGTYPE_p_tst_nodeTjchar_jobject_t get(int index) {
    long cPtr = tstJNI._ObjectMemoryStorage_get(swigCPtr, index);
    return (cPtr == 0) ? null : new SWIGTYPE_p_tst_nodeTjchar_jobject_t(cPtr, false);
  }

  public Object store_data(SWIGTYPE_p_tst_nodeTjchar_jobject_t node, Object data) {
    return tstJNI._ObjectMemoryStorage_store_data(swigCPtr, SWIGTYPE_p_tst_nodeTjchar_jobject_t.getCPtr(node), data);
  }

  public int new_node() {
    return tstJNI._ObjectMemoryStorage_new_node(swigCPtr);
  }

  public void delete_node(int index) {
    tstJNI._ObjectMemoryStorage_delete_node(swigCPtr, index);
  }

  public void pack() {
    tstJNI._ObjectMemoryStorage_pack(swigCPtr);
  }

  public void read(SWIGTYPE_p_FILE file, _ObjectSerializer reader, SWIGTYPE_p_int root, SWIGTYPE_p_int maximum_key_length, SWIGTYPE_p_jobject default_value) {
    tstJNI._ObjectMemoryStorage_read(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file), _ObjectSerializer.getCPtr(reader), SWIGTYPE_p_int.getCPtr(root), SWIGTYPE_p_int.getCPtr(maximum_key_length), SWIGTYPE_p_jobject.getCPtr(default_value));
  }

  public void write(SWIGTYPE_p_FILE file, _ObjectSerializer writer, int root, int maximum_key_length, Object default_value) {
    tstJNI._ObjectMemoryStorage_write(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file), _ObjectSerializer.getCPtr(writer), root, maximum_key_length, default_value);
  }

}
