/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class _ObjectAction {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _ObjectAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_ObjectAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected _ObjectAction() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete__ObjectAction(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void perform(String string, int remaining_distance, Object data) {
    tstJNI._ObjectAction_perform(swigCPtr, string, remaining_distance, data);
  }

  public Object result() {
    return tstJNI._ObjectAction_result(swigCPtr);
  }

}
