/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class LongAction extends _LongAction {
  private long swigCPtr;

  protected LongAction(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGLongActionUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected LongAction() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_LongAction(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public LongAction(Object target, String perform, String result) {
    this(tstJNI.new_LongAction(target, perform, result), true);
  }

  public void perform(String string, int remaining_distance, long data) {
    tstJNI.LongAction_perform(swigCPtr, string, remaining_distance, data);
  }

  public long result() {
    return tstJNI.LongAction_result(swigCPtr);
  }

}
