/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class LongSerializer extends _LongSerializer {
  private long swigCPtr;

  protected LongSerializer(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGLongSerializerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongSerializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_LongSerializer(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void write(SWIGTYPE_p_FILE file, long data) {
    tstJNI.LongSerializer_write(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file), data);
  }

  public long read(SWIGTYPE_p_FILE file) {
    return tstJNI.LongSerializer_read(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file));
  }

  public LongSerializer() {
    this(tstJNI.new_LongSerializer(), true);
  }

}
