/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class ObjectSerializer extends _ObjectSerializer {
  private long swigCPtr;

  protected ObjectSerializer(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGObjectSerializerUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectSerializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_ObjectSerializer(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public void write(SWIGTYPE_p_FILE file, Object data) {
    tstJNI.ObjectSerializer_write(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file), data);
  }

  public Object read(SWIGTYPE_p_FILE file) {
    return tstJNI.ObjectSerializer_read(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file));
  }

  public ObjectSerializer() {
    this(tstJNI.new_ObjectSerializer(), true);
  }

}
