/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class ObjectAction extends _ObjectAction {
  private long swigCPtr;

  protected ObjectAction(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGObjectActionUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected ObjectAction() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_ObjectAction(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ObjectAction(Object target, String perform, String result) {
    this(tstJNI.new_ObjectAction(target, perform, result), true);
  }

  public void perform(String string, int remaining_distance, Object data) {
    tstJNI.ObjectAction_perform(swigCPtr, string, remaining_distance, data);
  }

  public Object result() {
    return tstJNI.ObjectAction_result(swigCPtr);
  }

}
