/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class ObjectFilter extends _ObjectFilter {
  private long swigCPtr;

  protected ObjectFilter(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGObjectFilterUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected ObjectFilter() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_ObjectFilter(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ObjectFilter(Object target, String perform) {
    this(tstJNI.new_ObjectFilter(target, perform), true);
  }

  public Object perform(String string, int remaining_distance, Object data) {
    return tstJNI.ObjectFilter_perform(swigCPtr, string, remaining_distance, data);
  }

}
