/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lehuen.tst;

public class ObjectTST extends _ObjectTST {
  private long swigCPtr;

  protected ObjectTST(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGObjectTSTUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectTST obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected ObjectTST() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_ObjectTST(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ObjectTST(int initial_size, Object data) {
    this(tstJNI.new_ObjectTST(initial_size, data), true);
  }

}
