/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class _JavaTST {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _JavaTST(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_JavaTST obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected _JavaTST() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete__JavaTST(swigCPtr);
    }
    swigCPtr = 0;
  }

  public _JavaTST(SWIGTYPE_p_FILE file, _Serializer reader) {
    this(tstJNI.new__JavaTST__SWIG_0(SWIGTYPE_p_FILE.getCPtr(file), _Serializer.getCPtr(reader)), true);
  }

  public _JavaTST(int initial_size, Object default_value) {
    this(tstJNI.new__JavaTST__SWIG_1(initial_size, default_value), true);
  }

  public void pack() {
    tstJNI._JavaTST_pack(swigCPtr);
  }

  public Object walk(_Filter filter, _Action to_perform) {
    return tstJNI._JavaTST_walk(swigCPtr, _Filter.getCPtr(filter), _Action.getCPtr(to_perform));
  }

  public Object almost(String string, int string_length, int maximum_distance, _Filter filter, _Action to_perform) {
    return tstJNI._JavaTST_almost(swigCPtr, string, string_length, maximum_distance, _Filter.getCPtr(filter), _Action.getCPtr(to_perform));
  }

  public Object common_prefix(String string, _Filter filter, _Action to_perform) {
    return tstJNI._JavaTST_common_prefix(swigCPtr, string, _Filter.getCPtr(filter), _Action.getCPtr(to_perform));
  }

  public Object scan(String string, _Action to_perform) {
    return tstJNI._JavaTST_scan(swigCPtr, string, _Action.getCPtr(to_perform));
  }

  public Object scan_with_stop_chars(String string, String stop_chars, _Action to_perform) {
    return tstJNI._JavaTST_scan_with_stop_chars(swigCPtr, string, stop_chars, _Action.getCPtr(to_perform));
  }

  public Object get(String string) {
    return tstJNI._JavaTST_get(swigCPtr, string);
  }

  public Object get_or_build(String string, _Filter factory) {
    return tstJNI._JavaTST_get_or_build(swigCPtr, string, _Filter.getCPtr(factory));
  }

  public Object put(String string, Object data) {
    return tstJNI._JavaTST_put(swigCPtr, string, data);
  }

  public void remove(String string) {
    tstJNI._JavaTST_remove(swigCPtr, string);
  }

  public int get_maximum_key_length() {
    return tstJNI._JavaTST_get_maximum_key_length(swigCPtr);
  }

  public long bytes_allocated() {
    return tstJNI._JavaTST_bytes_allocated(swigCPtr);
  }

  public void write(SWIGTYPE_p_FILE file, _Serializer writer) {
    tstJNI._JavaTST_write(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file), _Serializer.getCPtr(writer));
  }

  public void debug_print_root() {
    tstJNI._JavaTST_debug_print_root(swigCPtr);
  }

}
