/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class _Serializer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _Serializer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_Serializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected _Serializer() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete__Serializer(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void write(SWIGTYPE_p_FILE file, Object data) {
    tstJNI._Serializer_write(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file), data);
  }

  public Object read(SWIGTYPE_p_FILE file) {
    return tstJNI._Serializer_read(swigCPtr, SWIGTYPE_p_FILE.getCPtr(file));
  }

}
