/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Action extends _Action {
  private long swigCPtr;

  protected Action(long cPtr, boolean cMemoryOwn) {
    super(tstJNI.SWIGActionUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Action obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected Action() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      tstJNI.delete_Action(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public Action(Object target, String perform, String result) {
    this(tstJNI.new_Action(target, perform, result), true);
  }

  public void perform(String key, int remaining_distance, Object data) {
    tstJNI.Action_perform(swigCPtr, key, remaining_distance, data);
  }

  public Object result() {
    return tstJNI.Action_result(swigCPtr);
  }

}
