/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class tstJNI {
  public final static native int get_UNDEFINED_INDEX();
  public final static native String get_TST_VERSION();
  public final static native long new_JavaTST__SWIG_0(long jarg1, long jarg2);
  public final static native long new_JavaTST__SWIG_1(int jarg1, String jarg2);
  public final static native void delete_JavaTST(long jarg1);
  public final static native void JavaTST_pack(long jarg1);
  public final static native String JavaTST_walk(long jarg1, long jarg2, long jarg3);
  public final static native String JavaTST_almost(long jarg1, String jarg2, int jarg3, int jarg4, long jarg5, long jarg6);
  public final static native String JavaTST_common_prefix(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native String JavaTST_scan(long jarg1, String jarg2, long jarg3);
  public final static native String JavaTST_scan_with_stop_chars(long jarg1, String jarg2, String jarg3, long jarg4);
  public final static native String JavaTST_get(long jarg1, String jarg2);
  public final static native String JavaTST_get_or_build(long jarg1, String jarg2, long jarg3);
  public final static native String JavaTST_put(long jarg1, String jarg2, String jarg3);
  public final static native void JavaTST_remove(long jarg1, String jarg2);
  public final static native int JavaTST_get_maximum_key_length(long jarg1);
  public final static native long JavaTST_bytes_allocated(long jarg1);
  public final static native void JavaTST_write(long jarg1, long jarg2, long jarg3);
  public final static native void JavaTST_debug_print_root(long jarg1);
  public final static native void delete_Action(long jarg1);
  public final static native void Action_perform(long jarg1, String jarg2, int jarg3, String jarg4);
  public final static native String Action_result(long jarg1);
  public final static native void delete_Filter(long jarg1);
  public final static native String Filter_perform(long jarg1, String jarg2, int jarg3, String jarg4);
  public final static native void delete_Serializer(long jarg1);
  public final static native void Serializer_write(long jarg1, long jarg2, String jarg3);
  public final static native String Serializer_read(long jarg1, long jarg2);
}
