/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class tstJNI {
  public final static native int get_UNDEFINED_INDEX();
  public final static native String get_TST_VERSION();
  public final static native long new__JavaTST__SWIG_0(long jarg1, long jarg2);
  public final static native long new__JavaTST__SWIG_1(int jarg1, Object jarg2);
  public final static native void delete__JavaTST(long jarg1);
  public final static native void _JavaTST_pack(long jarg1);
  public final static native Object _JavaTST_walk(long jarg1, long jarg2, long jarg3);
  public final static native Object _JavaTST_almost(long jarg1, String jarg2, int jarg3, int jarg4, long jarg5, long jarg6);
  public final static native Object _JavaTST_common_prefix(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native Object _JavaTST_scan(long jarg1, String jarg2, long jarg3);
  public final static native Object _JavaTST_scan_with_stop_chars(long jarg1, String jarg2, String jarg3, long jarg4);
  public final static native Object _JavaTST_get(long jarg1, String jarg2);
  public final static native Object _JavaTST_get_or_build(long jarg1, String jarg2, long jarg3);
  public final static native Object _JavaTST_put(long jarg1, String jarg2, Object jarg3);
  public final static native void _JavaTST_remove(long jarg1, String jarg2);
  public final static native int _JavaTST_get_maximum_key_length(long jarg1);
  public final static native long _JavaTST_bytes_allocated(long jarg1);
  public final static native void _JavaTST_write(long jarg1, long jarg2, long jarg3);
  public final static native void _JavaTST_debug_print_root(long jarg1);
  public final static native void delete__Action(long jarg1);
  public final static native void _Action_perform(long jarg1, String jarg2, int jarg3, Object jarg4);
  public final static native Object _Action_result(long jarg1);
  public final static native void delete__Filter(long jarg1);
  public final static native Object _Filter_perform(long jarg1, String jarg2, int jarg3, Object jarg4);
  public final static native void delete__Serializer(long jarg1);
  public final static native void _Serializer_write(long jarg1, long jarg2, Object jarg3);
  public final static native Object _Serializer_read(long jarg1, long jarg2);
  public final static native long new_JavaTST();
  public final static native void delete_JavaTST(long jarg1);
  public final static native long new_Action(Object jarg1);
  public final static native void Action_perform(long jarg1, String jarg2, int jarg3, Object jarg4);
  public final static native Object Action_result(long jarg1);
  public final static native void delete_Action(long jarg1);
  public final static native Object Filter_perform(long jarg1, String jarg2, int jarg3, Object jarg4);
  public final static native long new_Filter();
  public final static native void delete_Filter(long jarg1);
  public final static native void Serializer_write(long jarg1, long jarg2, Object jarg3);
  public final static native Object Serializer_read(long jarg1, long jarg2);
  public final static native long new_Serializer();
  public final static native void delete_Serializer(long jarg1);
  public final static native long SWIGJavaTSTUpcast(long jarg1);
  public final static native long SWIGActionUpcast(long jarg1);
  public final static native long SWIGFilterUpcast(long jarg1);
  public final static native long SWIGSerializerUpcast(long jarg1);
}
